#!/bin/bash

rm -f /tmp/rooomy_env 2>/dev/null
# Don't quote the spaces, docker does not interpret, just split, it seems
echo "ROOOMY_USER=web" >> /tmp/rooomy_env
echo "ROOOMY_PASSWORD=good to be a pv" >> /tmp/rooomy_env
echo "ROOOMY_ENVIRONMENT=mactest" >> /tmp/rooomy_env
echo "ROOOMY_ROLE=macmaster" >> /tmp/rooomy_env

docker run --rm --env-file /tmp/rooomy_env -p 8989:8989 rberwald/rooomy-exporter /rooomy-exporter -rooomy.scrape-uri 'https://rooomydev-master.loftweb.nl:8443' -log.format 'logger:stdout?json=true'
